services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - 8080:8080
    volumes:
      - ~/.cache/huggingface:/.cache/huggingface
  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    ports:
      - 5000:5000
    volumes:
      - ~/.cache/huggingface:/.cache/huggingface
