services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - 8080:8080
  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    ports:
      - 5000:5000
