FROM python:3.9

# install project requirements
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt
RUN pip install git+https://github.com/PrithivirajDamodaran/Parrot_Paraphraser.git

COPY . .

EXPOSE 8000

ENTRYPOINT python ./quotera_cli.py serve


